name: Pulling from Keboola
description: Pulling from Keboola
inputs:
  workdir:
    description: Working directory
    required: true
  kbcStorageApiToken:
    description: Keboola Connection Storage API Token
    required: true
  kbcProjectId:
    description: Keboola Connection Project ID
    required: true
  kbcBranchId:
    description: Keboola Connection Branch ID
    required: true
  githubToken:
    description: GitHub Workflow Token
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install
      with:
        githubToken: ${{ inputs.githubToken }}
    # Pull remote project's state
    - name: Pull L0 from Keboola Connection
      env:
        # filled by the script
        KBC_STORAGE_API_TOKEN: ${{ inputs.kbcStorageApiToken }}
        KBC_PROJECT_ID: ${{ inputs.kbcProjectId }}
        KBC_BRANCH_ID: ${{ inputs.kbcBranchId }}
        WORKDIR: ${{ inputs.workdir }}
      # filled by the script
      id: kbc_pull_L0_step
      run: |
        apt-get update && apt-get install -y jq
        chmod +x ./.github/scripts/pull.sh
        ./.github/scripts/pull.sh
      shell: bash