name: Check if artifact exists
description: Check if artifact exists
inputs:
  artifactName:
    description: Artifact name to check
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if artifact storage_structures_result exists
      uses: actions/github-script@v7
      with:
        script: |
          const artifactName = '${{ inputs.artifactName }}';
          const runId = process.env.GITHUB_RUN_ID;
          const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: runId,
          });
  
          const artifact = artifacts.artifacts.find(artifact => artifact.name === artifactName);
  
          if (artifact) {
            core.setOutput('artifact_exists', true);
          } else {
            core.setOutput('artifact_exists', false);
          }
