name: Keboola Project Detail
description: Get to the Keboola project detail
inputs:
  workdir:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        "echo" "Hello ! while Keboola secret validation $KBC_BRANCH_ID_${{ inputs.workdir }}"
        
        # Retrieve the input folder name
        FOLDER_NAME="${{ inputs.workdir }}"

        # Form the variable name based on the folder name
        VAR_NAME="\$${{ vars.KBC_PROJECT_ID_${FOLDER_NAME} }}"

        # Retrieve the variable value using indirect reference
        VALUE=$(eval echo \$$VAR_NAME)

        # Print the variable value
        echo "Value for ${VAR_NAME} is ${VALUE} or ${{ vars.KBC_PROJECT_ID_L1 }}"

      shell: bash
