name: Keboola Project Detail
description: Get to the Keboola project detail
inputs:
  source_workdir:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        "echo" "Hello ! while Keboola secret validation $KBC_BRANCH_ID_L0${{ inputs.source_workdir }}"
        
        # Retrieve the input folder name
        FOLDER_NAME="${{ inputs.source_workdir }}"

        # Form the variable name based on the folder name
        VAR_NAME="KBC_BRANCH_ID_${FOLDER_NAME}"

        # Retrieve the variable value using indirect reference
        VALUE=$(eval echo \$$VAR_NAME)

        # Print the variable value
        echo "Value for ${VAR_NAME} is ${VALUE}"

      shell: bash
