name: Keboola Storage validation pull
description: Pulling from Keboola project storage structure
inputs:
  destFile:
    description: Destination file
    required: true
  outFolder:
    description: Output folder
    required: true
  kbcStorageApiHost:
    description: Keboola Connection Stack URL
    required: true
  kbcStorageApiToken:
    description: Keboola Connection Storage API Token
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pull storage structure
      shell: bash
      run: |
        python3 .github/actions/kbc_storage_validation/pull/storage_pull.py \
          --host="${{ inputs.kbcStorageApiHost }}" \
          --token="${{ inputs.kbcStorageApiToken }}" \
          --destination-file="${{ inputs.outFolder }}/${{ inputs.destFile }}"

    - name: Save structure to artifact
      uses: actions/upload-artifact@v3
      with:
        name: projects_structure
        path: ${{ inputs.outFolder }}/*
        retention-days: 5
