name: Keboola as Code Install
description: Install Keboola as Code CLI
runs:
  using: "composite"
  steps:
    - id: prepare
      run: |
        mkdir "./kbc"
        apt-get update && apt-get install -y curl unzip git
      shell: bash
    # Extract binary
    - id: kbc_extract_release
      run: |
        latest_version=$(curl --silent -qI https://github.com/keboola/keboola-as-code/releases/latest | awk -F '/' '/^location/ {print  substr($NF, 1, length($NF)-1)}'); \
        file_name="keboola-cli_${latest_version:1}_linux_amd64.zip"
        target_url="https://github.com/keboola/keboola-as-code/releases/download/$latest_version/$file_name"
        release_zip="./kbc/$file_name"
        echo "Downloading $target_url" to "$release_zip"
        curl -L -o "$release_zip" "$target_url"
        
        if [ ! -f "$release_zip" ]; then
          echo "Could not download $file_name from the latest release."
          exit 1
        fi
        release_bin="/usr/local/bin/kbc"
        ls -l $release_zip
        chmod 644 $release_zip
        unzip "$release_zip" -d /usr/local/bin
        chmod +x "$release_bin"
        echo "Keboola as Code CLI installed: $release_bin"
        kbc --version
      shell: bash
