name: Manual Storage Diff All
on:
  workflow_dispatch:
    inputs:
      dest_env:
        description: 'Which environment to compare against (will be destination)'
        required: true
        default: ''
permissions:
  contents: write
jobs:
  get_current_branch_env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
         - environment: |-
            ${{
               github.ref_name == 'main' && 'prod'
            || github.ref_name == 'dev' && 'dev'
            }}
           type: "source"
         - environment: ${{ github.event.inputs.dest_env }}
           type: "destination"
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      # Dynamic generated value
      - name: Pull storage L0
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.type }}/${{ matrix.environment }}_L0.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L0 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L0 }}

      - name: Pull storage L1
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.type }}/${{ matrix.environment }}_L1.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L1 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L1 }}
       # END Dynamic generated value

      - name: Save variables to file
        uses: actions/upload-artifact@v3
        with:
          name: source_projects_structure
          path: .
          retention-days: 5
