name: Manual KBC Pull L0, L1
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Pull_All:
    # Generated value
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    env:
       # Generated value
       kbcUrl: "connection.keboola.com"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Pull configurations from L0
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L0"
          kbcUrl: ${{env.kbcUrl}}
          kbcStorageApiToken: ${{ secrets.L0_TOKEN }}
          kbcProjectId: ${{ vars.L0_PROJECT_ID }}
          kbcBranchId: ${{ vars.L0_BRANCH_ID }}
      
      - name: Pull configurations from L1
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L1"
          kbcUrl: ${{env.kbcUrl}}
          kbcStorageApiToken: ${{ secrets.L1_TOKEN }}
          kbcProjectId: ${{ vars.L1_PROJECT_ID }}
          kbcBranchId: ${{ vars.L1_BRANCH_ID }}
      # End generated steps

      - name: Commit and push
        run: |
          apt-get update && apt-get install -y tree
          tree -a
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push --force