name: Manual KBC Pull All
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Pull_All:
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull L0 from Keboola Connection
        uses: ./.github/actions/kbc_pull
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workdir: L0
          kbcUrl: "connection.keboola.com"
          kbcStorageApiToken: ${{ secrets.L0_TOKEN }}
          kbcProjectId: ${{ vars.L0_PROJECT_ID }}
          kbcBranchId: ${{ vars.L0_BRANCH_ID }}
      - name: Pull L1 from Keboola Connection
        uses: ./.github/actions/kbc_pull
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workdir: L1
          kbcUrl: "connection.keboola.com"
          kbcStorageApiToken: ${{ secrets.L1_TOKEN }}
          kbcProjectId: ${{ vars.L1_PROJECT_ID }}
          kbcBranchId: ${{ vars.L1_BRANCH_ID }}
      - name: Commit and push
        run: |
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push --force