name: Manual KBC Pull (L0, L1)
on:
  workflow_dispatch:
    inputs:
      dest_env:
        description: 'Which environment to compare against (will be destination)'
        default: ''
permissions:
  contents: write
jobs:

  storage_validation_get_structure:
    if: github.event.inputs.dest_env != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: |-
              ${{
                 github.ref_name == 'main' && 'prod'
              || github.ref_name == 'dev' && 'dev'
              }}
            origin: "source"
          - environment: ${{ github.event.inputs.dest_env }}
            origin: "destination"
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      # L0
      - name: Pull storage L0
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L0.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L0 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L0 }}

      # L1
      - name: Pull storage L1
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L1.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L1 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L1 }}

  storage_validation_comparison:
    runs-on: ubuntu-latest
    needs: storage_validation_get_structure
    steps:
      - uses: actions/checkout@v4

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: projects_structure
          pattern: projects_structure_*

      - name: Download structures
        uses: actions/download-artifact@v4
        with:
          name: projects_structure
          path: ./projects_structure

      - name: Compare storage structure
        shell: bash
        run: |
          ls
          python3 .github/actions/kbc_storage_validation/storage_diff/main.py \
            --workdir="./projects_structure" 

      - name: Save structure to artifact
        uses: actions/upload-artifact@v4
        with:
          name: projects_structure_result
          path: ./Storage_report.md
          retention-days: 5

      - name: Save message to output
        id: storage_report
        run: |
          echo "::set-output name=commit_message::$(cat ./Storage_report.md)"

  Pull_All:
    if: always()
    needs: [storage_validation_comparison]
    # Dynamic generated value
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Pull configurations from L0
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L0"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L0 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L0 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L0 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}

      - name: Pull configurations from L1
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L1"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L1 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L1 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L1 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L1 }}
      # End generated steps

      - name: Commit and push
        env:
          commit_message: ${{ steps.storage_report.outputs.commit_message }}
        run: |
          apt-get update && apt-get install -y tree
          tree -a
          currentDate=`date +%Y-%m-%d:%T%Z`
          
          commit_message+=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push --force