name: Manual KBC Push (L0, L1)
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Push_All:
    # Dynamic generated value
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Push configurations to L0
        uses: ./.github/actions/kbc_push
        with:
          workdir: "L0"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST_L0 }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L0 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L0 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}
      
      - name: Push configurations to L1
        uses: ./.github/actions/kbc_push
        with:
          workdir: "L1"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST_L1 }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L1 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L1 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L1 }}
      # End generated steps