name: Storage Diff All
on:
  workflow_dispatch:
    inputs:
      dest_env:
        description: 'Which environment to compare against (will be destination)'
        required: true
        default: ''
permissions:
  contents: write
jobs:
  storage_validation_get_structure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: |-
              ${{
                 github.ref_name == 'main' && 'prod'
              || github.ref_name == 'dev' && 'dev'
              }}
            origin: "source"
          - environment: ${{ github.event.inputs.dest_env }}
            origin: "destination"
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      # L0
      - name: Pull storage L0
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L0.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L0 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L0 }}

      # L1
      - name: Pull storage L1
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L1.json"
          kbcStorageApiHost: ${{ vars.KBC_STORAGE_API_HOST_L1 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L1 }}

  storage_validation_comparison:
    runs-on: ubuntu-latest
    needs: storage_validation_get_structure
    steps:
      - uses: actions/checkout@v4

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: projects_structure
          pattern: projects_structure_*

      - name: Download structures
        uses: actions/download-artifact@v4
        with:
          name: projects_structure
          path: ./projects_structure

      - name: Compare storage structure
        shell: bash
        run: |
          python3 .github/actions/kbc_storage_validation/storage_diff/main.py \
            --workdir="./projects_structure" 

      - name: Save structure to artifact
        uses: actions/upload-artifact@v4
        with:
          name: projects_structure_result
          path: ./Storage_report.md
          retention-days: 5

      - name: Commit and push changes
        run: |
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          commit_message=$(cat ./Storage_report.md)
          rm ./Storage_report.md
          rm -rf projects_structure
          git commit -m '$commit_message'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
