name: Manual KBC Push All
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Push_All:
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Push L0 to Keboola Connection
        uses: ./.github/actions/kbc_push
        with:
          workdir: L0
          kbcStorageApiToken: ${{ secrets.L0_TOKEN }}
          kbcProjectId: ${{ vars.L0_PROJECT_ID }}
          kbcBranchId: ${{ vars.L0_BRANCH_ID }}

      - name: Push L1 to Keboola Connection
        uses: ./.github/actions/kbc_push
        with:
          workdir: L1
          kbcStorageApiToken: ${{ secrets.L1_TOKEN }}
          kbcProjectId: ${{ vars.L1_PROJECT_ID }}
          kbcBranchId: ${{ vars.L1_BRANCH_ID }}