name: Manual Storage Diff All
on:
  workflow_dispatch:
    inputs:
      dest_env:
        description: 'Which environment to compare against (will be destination)'
        required: true
        default: ''
permissions:
  contents: write
env:
  current_environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' }}
jobs:
  get_current_branch_env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ $current_environment, "${{ github.event.inputs.dest_env }}" ]
    environment: ${{ matrix.environment }}
    steps:
      - name: Pull storage L0
        uses: ./.github/actions/kbc_storage_validation/pull
        with:
          environment: ${{ matrix.environment }}
          workdir: "L0"
          kbcStorageApiHost: ${{ secrets.KBC_STORAGE_API_HOST_L0 }}
          kbcStorageApiToken: ${{ secrets.KBC_STORAGE_API_TOKEN_L0 }}

      - name: Save variables to file
        uses: actions/upload-artifact@v3
        with:
          name: source_projects_structure
          path: .
          retention-days: 5
