name: Manual KBC Pull (L0, L1)
on:
  workflow_dispatch:
    inputs:
      dest_env:
        description: 'Which environment to compare against (will be destination)'
        default: ''
permissions:
  contents: write
jobs:

  # VAULT validation
  vault_validation_get_structures:
    if: github.event.inputs.dest_env != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: |-
              ${{
                 github.ref_name == 'main' && 'prod'
              || github.ref_name == 'dev' && 'dev'
              }}
            origin: "source"
          - environment: ${{ github.event.inputs.dest_env }}
            origin: "destination"
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      # L0
      - name: Pull vault L0
        uses: ./.github/actions/kbc_vault_validation/get_vault_keys
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L0.json"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L0 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}

      # L1
      - name: Pull vault L1
        uses: ./.github/actions/kbc_vault_validation/get_vault_keys
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L1.json"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L1 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}

  vault_validation_comparison:
    runs-on: ubuntu-latest
    needs: vault_validation_get_structures
    steps:
      - name: Compare vault structure
        uses: ./.github/actions/kbc_vault_validation

  # STORAGE validation
  storage_validation_get_structures:
    if: github.event.inputs.dest_env != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: |-
              ${{
                 github.ref_name == 'main' && 'prod'
              || github.ref_name == 'dev' && 'dev'
              }}
            origin: "source"
          - environment: ${{ github.event.inputs.dest_env }}
            origin: "destination"
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      # L0
      - name: Pull storage L0
        uses: ./.github/actions/kbc_storage_validation/get_storage_structure
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L0.json"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L0 }}

      # L1
      - name: Pull storage L1
        uses: ./.github/actions/kbc_storage_validation/get_storage_structure
        with:
          destFile: "${{ matrix.origin }}/${{ matrix.environment }}/L1.json"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L1 }}

  storage_validation_comparison:
    runs-on: ubuntu-latest
    needs: storage_validation_get_structures
    steps:
      - name: Compare storage structure
        uses: ./.github/actions/kbc_storage_validation

  # CLI push dry-run
  CLI_push_dry_run:
    if: github.event.inputs.dest_env != ''
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.dest_env }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # L0
      - name: Get CLI diff L0
        uses: ./.github/actions/kbc_push_dry
        with:
          workdir: "L0"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L0 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L0 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}

      # L1
      - name: Get CLI diff L1
        uses: ./.github/actions/kbc_push_dry
        with:
          workdir: "L1"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L1 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L1 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L1 }}

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: cli_diffs
          pattern: cli_diff_*

  # Pull all configurations from projects, collection of validation results and push with commit
  Pull_All:
    if: always()
    needs: [ storage_validation_comparison,vault_validation_comparison,CLI_push_dry_run ]
    # Dynamic generated value
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          currentDate=$(date +%Y-%m-%d:%T%Z)
          
          echo "Manual KBC pull $currentDate" > "$RUNNER_TEMP/log.txt"

      - uses: actions/checkout@v4

      # Vault artifacts downloading if exists
      - name: Download vault_structures_result if exists
        uses: ./.github/actions/download_artifact
        with:
          artifactName: vault_structures_result

      # Storage artifacts downloading if exists
      - name: Download vault_structures_result if exists
        uses: ./.github/actions/download_artifact
        with:
          artifactName: storage_structures_result

      # CLI diff artifacts downloading if exists
      - name: Download vault_structures_result if exists
        uses: ./.github/actions/download_artifact
        with:
          artifactName: cli_diffs

      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Pull configurations from L0
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L0"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L0 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L0 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L0 }}

      - name: Pull configurations from L1
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "L1"
          kbcSapiHost: ${{ vars.KBC_SAPI_HOST }}
          kbcSapiToken: ${{ secrets.KBC_SAPI_TOKEN_L1 }}
          kbcProjectId: ${{ vars.KBC_PROJECT_ID_L1 }}
          kbcBranchId: ${{ vars.KBC_BRANCH_ID_L1 }}
      # End generated steps

      # Final commit and GIT push
      - name: Commit and push
        env:
          commit_message: ${{ steps.storage_report.outputs.commit_message }}
        run: |
          # Commit and push
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          
          git add -A
          git commit --allow-empty -a -F "$RUNNER_TEMP/log.txt" || true
          git push --force
          
          


