name: Manual KBC Pull
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Prepare_environment:
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  Pull_L0:
    needs: Prepare_environment
    runs-on: ubuntu-latest
    steps:
      # Pull remote project's state
      - name: Pull L0 from Keboola Connection
        env:
          # filled by the script
          KBC_STORAGE_API_TOKEN: ${{ secrets.L0_TOKEN }}
          KBC_PROJECT_ID: ${{ vars.L0_PROJECT_ID }}
          KBC_BRANCH_ID: ${{ vars.L0_BRANCH_ID }}
          WORKDIR: L0
        # filled by the script
        id: kbc_pull_L0_step
        run: |
          apt-get update && apt-get install -y jq
          chmod +x ./.github/scripts/pull.sh
          ./.github/scripts/pull.sh
        shell: bash
  Pull_L1:
    needs: Prepare_environment
    runs-on: ubuntu-latest
    steps:
      # Pull remote project's state
      - name: Pull L1 from Keboola Connection
        env:
          # filled by the script
          KBC_STORAGE_API_TOKEN: ${{ secrets.L1_TOKEN }}
          KBC_PROJECT_ID: ${{ vars.L1_PROJECT_ID }}
          KBC_BRANCH_ID: ${{ vars.L1_BRANCH_ID }}
          WORKDIR: L1
        # filled by the script
        id: kbc_pull_L0_step
        run: |
          apt-get update && apt-get install -y jq
          chmod +x ./.github/scripts/pull.sh
          ./.github/scripts/pull.sh
        shell: bash
  Commit_and_push:
    needs: [ Pull_L0, Pull_L1 ]
    runs-on: ubuntu-latest
    steps:
      # Commit message contains date and output of the pull command
      - name: Commit and push
        run: |
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push