name: Manual KBC Pull
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  KBC_PULL:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Pull remote project's state
      # filled by the script
      - name: Pull L0 from Keboola Connection
        env:
          # filled by the script
          KBC_STORAGE_API_TOKEN: ${{ secrets.L0_TOKEN }}
        # filled by the script
        id: kbc_pull_L0_step
        run: |
          set -eo pipefail
          # filled by the script
          cd L0
          kbc pull --force 2>&1 | tee "$RUNNER_TEMP/log.txt"
      # Automatic pull can be canceled by push, wait a while
      - name: Wait
        run: sleep 20
      # Commit message contains date and output of the pull command
      - name: Commit and push
        run: |
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push