name: Manual KBC Pull
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  KBC_PULL:
    environment: |-
      ${{
         github.ref_name == 'main' && 'prod'
      || github.ref_name == 'dev' && 'dev'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Pull remote project's state
      # filled by the script
      - name: Pull L0 from Keboola Connection
        env:
          # filled by the script
          KBC_STORAGE_API_TOKEN: ${{ secrets.L0_TOKEN }}
          KBC_PROJECT_ID: ${{ vars.L0_PROJECT_ID }}
          KBC_BRANCH_ID: ${{ vars.L0_BRANCH_ID }}
          PROJECT: L0
        # filled by the script
        id: kbc_pull_L0_step
        run: scripts/tools/pull.sh "$KBC_STORAGE_API_TOKEN" "$KBC_PROJECT_ID" "$KBC_BRANCH_ID" "$PROJECT"
        shell: bash
      # Commit message contains date and output of the pull command
      - name: Commit and push
        run: |
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push