# This is a basic workflow to help you get started with Actions

name: KBC PULL

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  KBC_PULL:
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        env:
          L0_PROJECT_ID: ${{ vars.L0_PROJECT_ID }}
          L0_TOKEN: ${{ secrets.L0_TOKEN }}
        # Runs a set of commands using the runners shell
        run: |
          echo $L0_PROJECT_ID
          echo $L0_TOKEN
